### ISSUE TITLE
Nearby restaurants not working in Chrome

### ISSUE THREAD

**Issue by JannKleen** [resmio/portal#34]
chrome doesn't display the dialog at all, in safari it's working fine

**Comment by mmarder** [comment]
Doesnt work for me in chrome and safari. not sure what is going on.

**Comment by Atisheh** [comment]
according to this:
https://sites.google.com/a/chromium.org/dev/Home/chromium-security/deprecating-powerful-features-on-insecure-origins
our portal is no longer considered secure because we have http instead of https
Since Chrome 50 only secure origins are allowed which leads to our problem.

**Comment by nsb** [comment]
I will close this issue and add a new one for SSL.
