### ISSUE TITLE
Add more citys on restaurant-reservierungen.de

### ISSUE THREAD

**Issue by AnneResmio** [resmio/portal#6]
As we have a lot of customers in Nürnberg through Olga now, it would be great if we would add Nürnberg in restaurant-reservierungen.de so they can be found

**Comment by mmarder** [comment]
We should just add many more restaurants to the link list on the bottom of the page.
![bildschirmfoto 2015-07-01 um 17 10 22](https://cloud.githubusercontent.com/assets/1316291/8457873/1925cb8a-2014-11e5-91b6-6fffebcceb28.png)
